<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.core.date.moment_format_converter' shared service.

include_once $this->targetDirs[3].'\\vendor\\sonata-project\\core-bundle\\src\\Date\\MomentFormatConverter.php';

return $this->privates['sonata.core.date.moment_format_converter'] = new \Sonata\CoreBundle\Date\MomentFormatConverter();
