<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTLxIWS1\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTLxIWS1/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTLxIWS1.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTLxIWS1\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerTLxIWS1\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'TLxIWS1',
    'container.build_id' => '8b07da01',
    'container.build_time' => 1541755553,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTLxIWS1');
