<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJmRTFmN\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJmRTFmN/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJmRTFmN.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJmRTFmN\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJmRTFmN\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JmRTFmN',
    'container.build_id' => '3c42bf3f',
    'container.build_time' => 1541769920,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJmRTFmN');
